name: "todo-app"
services:
  db:
    image: postgres:latest
    container_name: db
    hostname: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: postgresdb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - todo-network
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    image: todo-backend:latest
    container_name: backend
    hostname: backend
    depends_on:
      - db
    restart: "unless-stopped"
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend/database:/app/database
    networks:
      - todo-network
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    image: todo-frontend:latest
    container_name: frontend
    hostname: frontend
    depends_on:
      - backend
    restart: "unless-stopped"
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
    networks:
      - todo-network
volumes:
  pgdata:
networks:
  todo-network:
    driver: bridge
