from .base_db import BaseDB

from psycopg_pool import ConnectionPool


class PostgreSQLDB(BaseDB):
    def __init__(self, conn_url: str):
        self._pool = ConnectionPool(
            conninfo=conn_url,
            min_size=5,
            max_size=10,
        )

    def create_connection(self):
        return self._pool.connection()

    def init_db(self):
        with self.create_connection() as conn:
            conn.execute("""
            CREATE TABLE IF NOT EXISTS todos (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title TEXT NOT NULL,
                description TEXT,
                is_active BOOLEAN,
                updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            )
            """)
